package com.shared.enums;

public enum Operation {
    CREATE_EMPLOYEE,
    READ_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    GET_ALL_EMPLOYEES,

    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    GET_ALL_PROJECTS,

    CREATE_DEPARTMENT,
    DELETE_DEPARTMENT,
    GET_ALL_DEPARTMENTS,

    CREATE_ROLE,
    DELETE_ROLE,
    GET_ALL_ROLES,

    GET_EMPLOYEES_BY_PROJECT,
    ASSIGN_EMPLOYEE_TO_PROJECT,
    REMOVE_EMPLOYEE_FROM_PROJECT,

    DISCONNECT
}